"""
solonats_batch.py — Solo Nationals batch-processing helpers.

Handles running the full build pipeline across a jobs JSON file,
chalk PNG regeneration, and metadata patching for the solonats archive.
"""

import json
import os
import re
import shutil
import sys

from track_core import merge_corrected_json

SCRIPT_DIR          = os.path.dirname(os.path.abspath(__file__))
GENERATED_DIR       = os.path.join(SCRIPT_DIR, 'generated')
SOLONATS_DETECT_DIR = os.path.join(GENERATED_DIR, 'solonats')


def regen_chalk_png(job, chalk_path):
    """Regenerate chalk PNG from the original PDF using full-page rendering."""
    pdf_path = job.get('pdf')
    page_num = job.get('page', 1)
    if not pdf_path or not os.path.isfile(pdf_path):
        return False
    try:
        import fitz
        from detect_chalk_lines import extract_chalk_paths, render_chalk_mask
        doc = fitz.open(pdf_path)
        page = doc[page_num - 1]
        chalk_paths = extract_chalk_paths(page)
        line_px = max(1, round(job.get('chalk_width', 5.0) / 12.0))
        chalk_img = render_chalk_mask(page, chalk_paths, line_width_px=line_px, dpi=72, centered=False)
        chalk_img.save(chalk_path)
        print(f"  Chalk PNG: {chalk_path} ({chalk_img.width}×{chalk_img.height} px)")
        return True
    except Exception as e:
        print(f"  WARNING: could not regenerate chalk PNG: {e}", file=sys.stderr)
        return False


def patch_solonats_metadata(dest_dir, track_name, designers, map_image_path):
    """Append designer credit and ezmac note to description; set ui/preview.png to the map image."""
    ui_path = os.path.join(dest_dir, track_name, 'ui', 'ui_track.json')
    if not os.path.isfile(ui_path):
        print(f"WARNING: ui_track.json not found at {ui_path}")
        return

    with open(ui_path, 'r', encoding='utf-8') as f:
        content = f.read()

    def _append(m):
        existing = m.group(1)
        suffix = (f' Designed by {designers}.' if designers else '') + ' Generated by ezmac.'
        return f'"description": "{existing}{suffix}"'

    updated = re.sub(r'"description"\s*:\s*"([^"]*)"', _append, content)
    with open(ui_path, 'w', encoding='utf-8') as f:
        f.write(updated)
    print(f"ui_track.json: appended credit (designers={designers!r})")

    if map_image_path and os.path.isfile(map_image_path):
        preview_path = os.path.join(dest_dir, track_name, 'ui', 'preview.png')
        shutil.copy2(map_image_path, preview_path)
        print(f"ui/preview.png <- {os.path.basename(map_image_path)}")
    else:
        print(f"WARNING: map image not found, preview.png not updated ({map_image_path})")


def run_jobs(jobs_path, only_names, fbx, blender_exe, generated_dir=None, build_fn=None):
    """Process a jobs JSON file, building each solonats track.

    build_fn: callable matching build_track.main() — called once per job with
    sys.argv pre-populated.  Pass build_track.main when calling from build_track.
    """
    with open(jobs_path) as f:
        jobs = json.load(f)

    only = set(only_names) if only_names else None
    errors = 0
    for job in jobs:
        name = job.get('name', '?')
        if job.get('skip'):
            print(f"  Skipping {name} (skip=true)")
            continue
        if only and name not in only:
            continue

        track_name = f'solonats_{name}'
        job_dir    = os.path.join(SOLONATS_DETECT_DIR, f'solonats_{name}')
        json_path  = os.path.join(job_dir, f'{name}.json')

        # Check for corrected JSON override
        if job.get('corrected_json'):
            corrected_path = job['corrected_json']
            if not os.path.isfile(corrected_path):
                print(f"ERROR: {name}: corrected_json specified but file not found: {corrected_path}",
                      file=sys.stderr)
                errors += 1
                continue
            print(f"  Using corrected JSON: {corrected_path}")
            # Merge page_w_pt/page_h_pt from auto-generated JSON if absent in corrected JSON,
            # then regenerate chalk PNG so it aligns with the full-page UV mapping in Blender.
            merged_path = os.path.join(job_dir, f'{name}_merged.json')
            merge_corrected_json(corrected_path, json_path, merged_path)
            chalk_path = os.path.splitext(merged_path)[0] + '_chalk.png'
            if not regen_chalk_png(job, chalk_path):
                # Fall back to copying any existing chalk PNG
                existing = os.path.join(job_dir, f'{name}_chalk.png')
                if os.path.isfile(existing):
                    shutil.copy2(existing, chalk_path)
            json_path = merged_path

        if not os.path.isfile(json_path):
            print(f"ERROR: {name}: detected JSON not found at {json_path} — "
                  f"run run_pdf_detection.py first", file=sys.stderr)
            errors += 1
            continue

        # Regenerate chalk PNG if it doesn't exist or is stale, ensuring full-page alignment
        chalk_path = os.path.splitext(json_path)[0] + '_chalk.png'
        json_mtime = os.path.getmtime(json_path)
        chalk_missing = not os.path.isfile(chalk_path)
        chalk_stale = os.path.isfile(chalk_path) and os.path.getmtime(chalk_path) < json_mtime
        if chalk_missing or chalk_stale:
            regen_chalk_png(job, chalk_path)

        print(f"\n{'='*65}")
        print(f"  Track: {track_name}")
        print(f"  JSON:  {json_path}")
        print(f"{'='*65}\n")

        # Build sys.argv for the single-track build_fn to parse
        argv = [
            sys.argv[0],
            '--name',        track_name,
            '--json',        json_path,
            '--no-template',
        ]
        if fbx:
            argv.append('--fbx')
        if blender_exe:
            argv += ['--blender', blender_exe]
        if generated_dir:
            argv += ['--generated-dir', generated_dir]

        old_argv = sys.argv
        sys.argv = argv
        failed = False
        try:
            build_fn()
        except SystemExit as e:
            if e.code and e.code != 0:
                print(f"ERROR building {track_name}: exit {e.code}", file=sys.stderr)
                errors += 1
                failed = True
        finally:
            sys.argv = old_argv

        if not failed:
            # Extract designers from the PDF parent folder (e.g. "2009 Chris Cox, Michael Feldpusch")
            pdf_path = job.get('pdf', '')
            designers = ''
            if pdf_path:
                folder = os.path.basename(os.path.dirname(pdf_path))
                designers = re.sub(r'^\d{4}\s+', '', folder)
            map_image = os.path.join(job_dir, f'{name}_map.png')
            track_dest = os.path.join(generated_dir or GENERATED_DIR, track_name)
            patch_solonats_metadata(track_dest, track_name, designers, map_image)

    if errors:
        sys.exit(f"{errors} job(s) failed")
